<?php

namespace Modules\TitanCore\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Modules\TitanCore\Services\ModulePersistence\TitanModuleManifestSnapshotStore;

/**
 * Caches all loaded module manifests (module.json) to a single PHP file
 * for fast production boot — avoids re-parsing JSON on every request.
 *
 * The cache file is written to the application's bootstrap/cache directory
 * (configurable via TITAN_MANIFEST_CACHE_PATH or titan-modules.manifest_cache_path).
 *
 * Usage:
 *   php artisan modules:manifest-cache           # write / refresh cache
 *   php artisan modules:manifest-cache --clear   # delete the cache file
 *
 * Exit codes:
 *   0 — success
 *   1 — error (e.g. no modules found, write failure)
 */
class ModulesManifestCacheCommand extends Command
{
    protected $signature = 'modules:manifest-cache
                            {--clear : Delete the manifest cache file instead of writing it}';

    protected $description = 'Cache all module manifests (module.json) for fast production boot.';

    /** Default cache file name, written to bootstrap/cache/. */
    public const CACHE_FILENAME = 'titan_manifests.php';

    public function handle(TitanModuleManifestSnapshotStore $snapshotStore): int
    {
        $cachePath = $this->resolveCachePath();

        if ($this->option('clear')) {
            return $this->clearCache($cachePath);
        }

        return $this->buildCache($cachePath, $snapshotStore);
    }

    // ──────────────────────────────────────────────────────────────────────────

    private function buildCache(string $cachePath, TitanModuleManifestSnapshotStore $snapshotStore): int
    {
        $modulesBase = base_path(config('titan-modules.path', 'Modules'));

        if (! is_dir($modulesBase)) {
            $this->components->error("Modules directory not found: {$modulesBase}");

            return self::FAILURE;
        }

        $manifests = [];
        $scanned = 0;
        $failed = 0;

        foreach (File::directories($modulesBase) as $moduleDir) {
            $moduleName = basename($moduleDir);
            $manifestPath = $moduleDir . '/module.json';

            if (! file_exists($manifestPath)) {
                $this->line("  <fg=yellow>⚠</> <fg=cyan>{$moduleName}</>: module.json not found — skipping");
                continue;
            }

            $raw = file_get_contents($manifestPath);
            $data = json_decode($raw, true);

            if (json_last_error() !== JSON_ERROR_NONE) {
                $failed++;
                $this->line("  <fg=red>✗</> <fg=cyan>{$moduleName}</>: invalid JSON — " . json_last_error_msg());
                continue;
            }

            $manifests[$moduleName] = $data;
            $snapshotStore->sync($moduleName, $data);
            $scanned++;
        }

        if ($scanned === 0) {
            $this->components->warn('No valid module manifests found. Cache not written.');

            return self::FAILURE;
        }

        // Build the PHP cache file
        $cacheDir = dirname($cachePath);
        if (! is_dir($cacheDir)) {
            File::makeDirectory($cacheDir, 0755, true);
        }

        $php = $this->renderCacheFile($manifests);
        $result = file_put_contents($cachePath, $php);

        if ($result === false) {
            $this->components->error("Failed to write cache file: {$cachePath}");

            return self::FAILURE;
        }

        $this->components->info(
            sprintf(
                'Manifest cache written: %d module(s) cached to %s',
                $scanned,
                $cachePath
            )
        );

        if ($failed > 0) {
            $this->components->warn("{$failed} module(s) had invalid manifests and were skipped.");
        }

        return self::SUCCESS;
    }

    private function clearCache(string $cachePath): int
    {
        if (! file_exists($cachePath)) {
            $this->components->warn("Manifest cache file does not exist: {$cachePath}");

            return self::SUCCESS;
        }

        if (! unlink($cachePath)) {
            $this->components->error("Failed to delete cache file: {$cachePath}");

            return self::FAILURE;
        }

        $this->components->info("Manifest cache cleared: {$cachePath}");

        return self::SUCCESS;
    }

    /**
     * Render the PHP cache file content.
     *
     * @param array<string, array<string, mixed>> $manifests
     */
    private function renderCacheFile(array $manifests): string
    {
        $timestamp = date('Y-m-d H:i:s');
        $count = count($manifests);
        $exported = var_export($manifests, true);

        return <<<PHP
<?php

/**
 * Titan Module Manifest Cache
 *
 * Auto-generated by `php artisan modules:manifest-cache`.
 * Generated at: {$timestamp}
 * Module count: {$count}
 *
 * DO NOT EDIT MANUALLY — regenerate with `php artisan modules:manifest-cache`.
 */

return {$exported};
PHP;
    }

    /**
     * Resolve the absolute path to the cache file.
     */
    private function resolveCachePath(): string
    {
        $configured = config('titan-modules.manifest_cache_path');

        if (! empty($configured)) {
            // If it's an absolute path use it directly; otherwise treat as relative to base_path()
            return str_starts_with($configured, '/')
                ? $configured
                : base_path($configured);
        }

        return base_path('bootstrap/cache/' . self::CACHE_FILENAME);
    }
}
